// Generate the paper's data tables as standalone LaTeX (booktabs) fragments under
// paper/tables/, straight from stats.json. The main.tex \input{}s these, so every
// number in a table is the same number the figures draw — regenerate with one
// command and nothing drifts.
//
// Run:  npx tsx paper/scripts/gen_tables.ts

import fs from "node:fs";
import path from "node:path";
import { FIG_DIR, loadGraph, modelLabels, modelVendors, REPO_ROOT, vendorNames } from "./figlib";

const TABLE_DIR = path.join(REPO_ROOT, "paper/tables");

interface Stats {
  meta: { totalAnswers: number; nModels: number; nVendors: number; nLanguages: number };
  summary: { overallSelfRate: number; confusionRate: number; refusedRate: number; unknownRate: number };
  byVariant: Record<string, Rec>;
  byLang: Record<string, Rec>;
  byVendor: Record<string, Rec>;
  byModel: Record<string, Rec>;
  byVendorVariant: Record<string, Rec>;
  imitationBalance: { vendor: string; imitated: number; imitates: number; net: number }[];
  imitationDegree: { vendor: string; inDeg: number; outDeg: number; net: number }[];
  langFragility: { modelId: string; vendor: string; min: number; minLang: string; max: number; maxLang: string; mean: number; range: number }[];
  abstention: { vendor: string; unknown: number; refused: number; total: number }[];
  crossEdges: { from: string; to: string; count: number; total: number; probability: number; byLang: Record<string, { count: number; total: number; p: number }> }[];
}
interface Rec {
  n: number;
  self: number;
  cross: number;
  refused: number;
  unknown: number;
}

const pct = (x: number, d = 1) => (x * 100).toFixed(d);
// Escape the few LaTeX specials that can appear in vendor/model display names.
const tex = (s: string) => s.replace(/([&%#_$])/g, "\\$1").replace(/–/g, "--");

function main() {
  const g = loadGraph();
  const stats = JSON.parse(fs.readFileSync(path.join(FIG_DIR, "stats.json"), "utf8")) as Stats;
  const vnames = vendorNames(g);
  const mlabels = modelLabels(g);
  const mvendor = modelVendors(g);
  const lname: Record<string, string> = {};
  for (const l of g.languages) lname[l.code] = l.name;
  // TABLE language labels must be Fandol-safe: the paper is typeset with
  // `fontset=fandol`, which covers Han but NOT Hangul/Cyrillic — so a native name
  // like "한국어"/"Русский" in a table renders as tofu (▯▯▯). (The FIGURES are
  // immune: resvg rasterizes them with the bundled Noto Sans SC, which has full
  // coverage.) For tables we therefore use Chinese language names — natural in a
  // Chinese report and guaranteed to render. Keep `lname` (native) for any
  // figure-facing use; use `lzh` for every \input table string.
  const LZH: Record<string, string> = {
    en: "英语",
    "zh-Hans": "简体中文",
    "zh-Hant": "繁体中文",
    ja: "日语",
    ko: "韩语",
    ru: "俄语",
    es: "西班牙语",
    fr: "法语",
    de: "德语",
    pt: "葡萄牙语",
  };
  const lzh = (code: string) => LZH[code] ?? lname[code] ?? code;
  fs.mkdirSync(TABLE_DIR, { recursive: true });

  // ---- Table: per-vendor outcome composition (sorted by self asc) ----
  {
    const rows = Object.entries(stats.byVendor)
      .map(([id, r]) => ({ id, ...r }))
      .sort((a, b) => a.self - b.self);
    const lines = [
      "% AUTO-GENERATED by paper/scripts/gen_tables.ts — do not edit by hand.",
      "\\begin{tabular}{l r r r r r}",
      "\\toprule",
      "厂商 Vendor & $n$ & 自指\\% & 跨厂\\% & 拒答\\% & 无身份\\% \\\\",
      "\\midrule",
    ];
    for (const r of rows) {
      lines.push(
        `${tex(vnames[r.id] ?? r.id)} & ${r.n} & ${pct(r.self)} & ${pct(r.cross)} & ${pct(r.refused)} & ${pct(r.unknown)} \\\\`,
      );
    }
    lines.push("\\midrule");
    const s = stats.summary;
    lines.push(
      `\\textbf{合计 All} & ${stats.meta.totalAnswers} & ${pct(s.overallSelfRate)} & ${pct(s.confusionRate)} & ${pct(s.refusedRate)} & ${pct(s.unknownRate)} \\\\`,
    );
    lines.push("\\bottomrule", "\\end{tabular}");
    write("tab_vendor.tex", lines.join("\n"));
  }

  // ---- Table: per-variant gradient ----
  {
    const order = ["bare", "probed", "debrand"];
    const zh: Record<string, string> = { bare: "变体一 裸问", probed: "变体二 追问", debrand: "变体三 去品牌越狱" };
    const lines = [
      "% AUTO-GENERATED by paper/scripts/gen_tables.ts",
      "\\begin{tabular}{l r r r r r}",
      "\\toprule",
      "提问变体 Variant & $n$ & 自指\\% & 跨厂\\% & 拒答\\% & 无身份\\% \\\\",
      "\\midrule",
    ];
    for (const k of order) {
      const r = stats.byVariant[k];
      lines.push(`${zh[k]} & ${r.n} & ${pct(r.self)} & ${pct(r.cross)} & ${pct(r.refused)} & ${pct(r.unknown)} \\\\`);
    }
    lines.push("\\bottomrule", "\\end{tabular}");
    write("tab_variant.tex", lines.join("\n"));
  }

  // ---- Table: per-language outcome (sorted by cross desc) ----
  {
    const rows = Object.entries(stats.byLang)
      .map(([code, r]) => ({ code, ...r }))
      .sort((a, b) => b.cross - a.cross);
    const lines = [
      "% AUTO-GENERATED by paper/scripts/gen_tables.ts",
      "\\begin{tabular}{l r r r r}",
      "\\toprule",
      "语言 Language & 自指\\% & 跨厂\\% & 拒答\\% & 无身份\\% \\\\",
      "\\midrule",
    ];
    for (const r of rows) {
      lines.push(`${tex(lzh(r.code))} & ${pct(r.self)} & ${pct(r.cross)} & ${pct(r.refused)} & ${pct(r.unknown)} \\\\`);
    }
    lines.push("\\bottomrule", "\\end{tabular}");
    write("tab_lang.tex", lines.join("\n"));
  }

  // ---- Table: per-model (all 27, sorted by self asc) ----
  {
    const rows = Object.entries(stats.byModel)
      .map(([id, r]) => ({ id, ...r }))
      .sort((a, b) => a.self - b.self);
    const lines = [
      "% AUTO-GENERATED by paper/scripts/gen_tables.ts",
      "\\begin{tabular}{l l r r r r}",
      "\\toprule",
      "模型 Model & 厂商 & 自指\\% & 跨厂\\% & 拒答\\% & 无身份\\% \\\\",
      "\\midrule",
    ];
    for (const r of rows) {
      lines.push(
        `${tex(mlabels[r.id] ?? r.id)} & ${tex(vnames[mvendor[r.id]] ?? mvendor[r.id])} & ${pct(r.self)} & ${pct(r.cross)} & ${pct(r.refused)} & ${pct(r.unknown)} \\\\`,
      );
    }
    lines.push("\\bottomrule", "\\end{tabular}");
    write("tab_model.tex", lines.join("\n"));
  }

  // ---- Table: top cross-vendor edges (real -> real different vendor) ----
  {
    const top = stats.crossEdges.slice(0, 12);
    const lines = [
      "% AUTO-GENERATED by paper/scripts/gen_tables.ts",
      "\\begin{tabular}{l l r r l}",
      "\\toprule",
      "真实厂商 & 被错认为 & 次数 & 占该厂\\% & 主要语言 (rate) \\\\",
      "\\midrule",
    ];
    for (const e of top) {
      const langs = Object.entries(e.byLang)
        .map(([c, b]) => ({ c, p: b.p }))
        .sort((a, b) => b.p - a.p)
        .slice(0, 2)
        .map((x) => `${tex(lzh(x.c))} ${pct(x.p, 0)}\\%`)
        .join(", ");
      lines.push(
        `${tex(vnames[e.from] ?? e.from)} & ${tex(vnames[e.to] ?? e.to)} & ${e.count} & ${pct(e.probability)} & ${langs} \\\\`,
      );
    }
    lines.push("\\bottomrule", "\\end{tabular}");
    write("tab_edges.tex", lines.join("\n"));
  }

  // ---- Table: manufacturer-level imitation balance (sorted by net desc) ----
  // Twin of fig_imitation_balance + the web Data Explorer's ImitationBalanceCard.
  {
    const rows = stats.imitationBalance.filter((r) => r.imitated > 0 || r.imitates > 0);
    const lines = [
      "% AUTO-GENERATED by paper/scripts/gen_tables.ts",
      "\\begin{tabular}{l r r r}",
      "\\toprule",
      "厂商 Vendor & 被冒认 & 冒认他人 & 净值 net \\\\",
      "\\midrule",
    ];
    for (const r of rows) {
      const net = r.net > 0 ? `$+$${r.net}` : `$-$${Math.abs(r.net)}`;
      lines.push(`${tex(vnames[r.vendor] ?? r.vendor)} & ${r.imitated} & ${r.imitates} & ${net} \\\\`);
    }
    lines.push("\\bottomrule", "\\end{tabular}");
    write("tab_imitation.tex", lines.join("\n"));
  }

  // ---- Table: imitation DEGREE — distinct-vendor edge counts (threshold 0). ----
  // Companion to tab_imitation: every (from→to) pair counts once. in = how many
  // distinct vendors imitate it; out = how many distinct real vendors it imitates.
  {
    const rows = stats.imitationDegree.filter((r) => r.inDeg > 0 || r.outDeg > 0);
    const lines = [
      "% AUTO-GENERATED by paper/scripts/gen_tables.ts",
      "\\begin{tabular}{l r r r}",
      "\\toprule",
      "厂商 Vendor & 入度 in & 出度 out & 净边数 net \\\\",
      "\\midrule",
    ];
    for (const r of rows) {
      const net = r.net > 0 ? `$+$${r.net}` : r.net < 0 ? `$-$${Math.abs(r.net)}` : "0";
      lines.push(`${tex(vnames[r.vendor] ?? r.vendor)} & ${r.inDeg} & ${r.outDeg} & ${net} \\\\`);
    }
    lines.push("\\bottomrule", "\\end{tabular}");
    write("tab_imitation_degree.tex", lines.join("\n"));
  }

  // ---- Macro file: headline numbers as \newcommand so prose stays in sync ----
  {
    const s = stats.summary;
    const m = stats.meta;
    const bare = stats.byVariant.bare,
      probed = stats.byVariant.probed,
      debrand = stats.byVariant.debrand;
    const def = (name: string, val: string) => `\\newcommand{\\${name}}{${val}}`;

    // Imitation balance: pull the three biggest "creditors" (imitated) and the
    // single biggest "debtor" (imitates) for the prose.
    const ib = stats.imitationBalance;
    const byVendorIB: Record<string, { imitated: number; imitates: number; net: number }> = {};
    for (const r of ib) byVendorIB[r.vendor] = r;
    const topImitator = [...ib].sort((a, b) => b.imitates - a.imitates)[0];
    // CANONICAL total cross-vendor claims = confusionRate × totalAnswers (= 2112).
    // This includes targets that are NOT tested vendors — untested real brands
    // (Meta, Mistral) and `other:<brand>` phantoms (Microsoft, Yandex) — so it is
    // the same denominator the abstract's \statCross (7.1%) is computed against.
    // (The imitationBalance `imitated` column only sums over tested targets, which
    // would undercount; we deliberately use the headline denominator here.)
    const totalCross = Math.round(s.confusionRate * m.totalAnswers);
    const anchorsImitated =
      (byVendorIB.anthropic?.imitated ?? 0) + (byVendorIB.openai?.imitated ?? 0) + (byVendorIB.google?.imitated ?? 0);

    // Imitation degree (binarized edges): top in-degree creditor & top out-degree
    // debtor, for the prose.
    const deg = stats.imitationDegree;
    const byVendorDeg: Record<string, { inDeg: number; outDeg: number }> = {};
    for (const r of deg) byVendorDeg[r.vendor] = r;
    const topInDeg = [...deg].sort((a, b) => b.inDeg - a.inDeg)[0];
    const topOutDeg = [...deg].sort((a, b) => b.outDeg - a.outDeg)[0];

    // Language fragility: the single widest-span model.
    const frag = stats.langFragility[0];
    // Abstention: inclusionAI's refused share.
    const incl = stats.abstention.find((a) => a.vendor === "inclusionai");

    const lines = [
      "% AUTO-GENERATED headline macros — \\input before \\begin{document}.",
      def("statTotal", String(m.totalAnswers)),
      def("statModels", String(m.nModels)),
      def("statVendors", String(m.nVendors)),
      def("statLangs", String(m.nLanguages)),
      def("statSelf", pct(s.overallSelfRate)),
      def("statCross", pct(s.confusionRate)),
      def("statRefused", pct(s.refusedRate)),
      def("statUnknown", pct(s.unknownRate)),
      def("statBareCross", pct(bare.cross)),
      def("statBareN", String(bare.n)),
      def("statProbedCross", pct(probed.cross)),
      def("statProbedN", String(probed.n)),
      def("statDebrandCross", pct(debrand.cross)),
      def("statDebrandN", String(debrand.n)),
      def("statBareSelf", pct(bare.self)),
      def("statProbedSelf", pct(probed.self)),
      def("statDebrandSelf", pct(debrand.self)),
      def("statDebrandRefused", pct(debrand.refused)),
      def("statProbedRefused", pct(probed.refused)),
      // Imitation balance headline numbers.
      def("statTotalCross", String(totalCross)),
      def("statAnchorsShare", pct(anchorsImitated / totalCross, 1)),
      def("statAnthroNet", `+${byVendorIB.anthropic?.net ?? 0}`),
      def("statAnthroImitated", String(byVendorIB.anthropic?.imitated ?? 0)),
      def("statOpenaiNet", `+${byVendorIB.openai?.net ?? 0}`),
      def("statGoogleNet", `+${byVendorIB.google?.net ?? 0}`),
      def("statTopImitator", tex(vnames[topImitator.vendor] ?? topImitator.vendor)),
      def("statTopImitatorOut", String(topImitator.imitates)),
      def("statTencentNet", String(byVendorIB.tencent?.net ?? 0)),
      def("statDoubaoNet", String(byVendorIB.bytedance?.net ?? 0)),
      def("statZaiNet", String(byVendorIB["z-ai"]?.net ?? 0)),
      // Imitation degree (binarized edges, threshold 0).
      def("statTopInDeg", tex(vnames[topInDeg.vendor] ?? topInDeg.vendor)),
      def("statTopInDegN", String(topInDeg.inDeg)),
      def("statTopOutDeg", tex(vnames[topOutDeg.vendor] ?? topOutDeg.vendor)),
      def("statTopOutDegN", String(topOutDeg.outDeg)),
      def("statAnthroInDeg", String(byVendorDeg.anthropic?.inDeg ?? 0)),
      def("statAnthroOutDeg", String(byVendorDeg.anthropic?.outDeg ?? 0)),
      // Language fragility headline (widest-span model).
      def("statFragModel", tex(mlabels[frag.modelId] ?? frag.modelId)),
      def("statFragMin", pct(frag.min, 0)),
      def("statFragMinLang", tex(lzh(frag.minLang))),
      def("statFragMax", pct(frag.max, 0)),
      def("statFragMaxLang", tex(lzh(frag.maxLang))),
      // Abstention headline.
      def("statInclRefused", pct(incl?.refused ?? 0)),
    ];
    write("macros.tex", lines.join("\n"));
  }

  console.log("tables + macros written to paper/tables/");
}

function write(name: string, body: string) {
  const dest = path.join(TABLE_DIR, name);
  fs.writeFileSync(dest, body + "\n", "utf8");
  console.log(`  wrote ${path.relative(REPO_ROOT, dest)}`);
}

main();
