// Generate the paper's data tables as standalone LaTeX (booktabs) fragments under
// paper/tables/, straight from stats.json. The main.tex \input{}s these, so every
// number in a table is the same number the figures draw — regenerate with one
// command and nothing drifts.
//
// Run:  npx tsx paper/scripts/gen_tables.ts

import fs from "node:fs";
import path from "node:path";
import { FIG_DIR, loadGraph, modelLabels, modelVendors, REPO_ROOT, vendorNames } from "./figlib";

const TABLE_DIR = path.join(REPO_ROOT, "paper/tables");

interface Stats {
  meta: { totalAnswers: number; nModels: number; nVendors: number; nLanguages: number };
  summary: { overallSelfRate: number; confusionRate: number; refusedRate: number; unknownRate: number };
  byVariant: Record<string, Rec>;
  byLang: Record<string, Rec>;
  byVendor: Record<string, Rec>;
  byModel: Record<string, Rec>;
  byVendorVariant: Record<string, Rec>;
  crossEdges: { from: string; to: string; count: number; total: number; probability: number; byLang: Record<string, { count: number; total: number; p: number }> }[];
}
interface Rec {
  n: number;
  self: number;
  cross: number;
  refused: number;
  unknown: number;
}

const pct = (x: number, d = 1) => (x * 100).toFixed(d);
// Escape the few LaTeX specials that can appear in vendor/model display names.
const tex = (s: string) => s.replace(/([&%#_$])/g, "\\$1").replace(/–/g, "--");

function main() {
  const g = loadGraph();
  const stats = JSON.parse(fs.readFileSync(path.join(FIG_DIR, "stats.json"), "utf8")) as Stats;
  const vnames = vendorNames(g);
  const mlabels = modelLabels(g);
  const mvendor = modelVendors(g);
  const lname: Record<string, string> = {};
  for (const l of g.languages) lname[l.code] = l.name;
  fs.mkdirSync(TABLE_DIR, { recursive: true });

  // ---- Table: per-vendor outcome composition (sorted by self asc) ----
  {
    const rows = Object.entries(stats.byVendor)
      .map(([id, r]) => ({ id, ...r }))
      .sort((a, b) => a.self - b.self);
    const lines = [
      "% AUTO-GENERATED by paper/scripts/gen_tables.ts — do not edit by hand.",
      "\\begin{tabular}{l r r r r r}",
      "\\toprule",
      "厂商 Vendor & $n$ & 自指\\% & 跨厂\\% & 拒答\\% & 无身份\\% \\\\",
      "\\midrule",
    ];
    for (const r of rows) {
      lines.push(
        `${tex(vnames[r.id] ?? r.id)} & ${r.n} & ${pct(r.self)} & ${pct(r.cross)} & ${pct(r.refused)} & ${pct(r.unknown)} \\\\`,
      );
    }
    lines.push("\\midrule");
    const s = stats.summary;
    lines.push(
      `\\textbf{合计 All} & ${stats.meta.totalAnswers} & ${pct(s.overallSelfRate)} & ${pct(s.confusionRate)} & ${pct(s.refusedRate)} & ${pct(s.unknownRate)} \\\\`,
    );
    lines.push("\\bottomrule", "\\end{tabular}");
    write("tab_vendor.tex", lines.join("\n"));
  }

  // ---- Table: per-variant gradient ----
  {
    const order = ["bare", "probed", "debrand"];
    const zh: Record<string, string> = { bare: "变体一 裸问", probed: "变体二 追问", debrand: "变体三 去品牌越狱" };
    const lines = [
      "% AUTO-GENERATED by paper/scripts/gen_tables.ts",
      "\\begin{tabular}{l r r r r r}",
      "\\toprule",
      "提问变体 Variant & $n$ & 自指\\% & 跨厂\\% & 拒答\\% & 无身份\\% \\\\",
      "\\midrule",
    ];
    for (const k of order) {
      const r = stats.byVariant[k];
      lines.push(`${zh[k]} & ${r.n} & ${pct(r.self)} & ${pct(r.cross)} & ${pct(r.refused)} & ${pct(r.unknown)} \\\\`);
    }
    lines.push("\\bottomrule", "\\end{tabular}");
    write("tab_variant.tex", lines.join("\n"));
  }

  // ---- Table: per-language outcome (sorted by cross desc) ----
  {
    const rows = Object.entries(stats.byLang)
      .map(([code, r]) => ({ code, ...r }))
      .sort((a, b) => b.cross - a.cross);
    const lines = [
      "% AUTO-GENERATED by paper/scripts/gen_tables.ts",
      "\\begin{tabular}{l r r r r}",
      "\\toprule",
      "语言 Language & 自指\\% & 跨厂\\% & 拒答\\% & 无身份\\% \\\\",
      "\\midrule",
    ];
    for (const r of rows) {
      lines.push(`${tex(lname[r.code] ?? r.code)} & ${pct(r.self)} & ${pct(r.cross)} & ${pct(r.refused)} & ${pct(r.unknown)} \\\\`);
    }
    lines.push("\\bottomrule", "\\end{tabular}");
    write("tab_lang.tex", lines.join("\n"));
  }

  // ---- Table: per-model (all 27, sorted by self asc) ----
  {
    const rows = Object.entries(stats.byModel)
      .map(([id, r]) => ({ id, ...r }))
      .sort((a, b) => a.self - b.self);
    const lines = [
      "% AUTO-GENERATED by paper/scripts/gen_tables.ts",
      "\\begin{tabular}{l l r r r r}",
      "\\toprule",
      "模型 Model & 厂商 & 自指\\% & 跨厂\\% & 拒答\\% & 无身份\\% \\\\",
      "\\midrule",
    ];
    for (const r of rows) {
      lines.push(
        `${tex(mlabels[r.id] ?? r.id)} & ${tex(vnames[mvendor[r.id]] ?? mvendor[r.id])} & ${pct(r.self)} & ${pct(r.cross)} & ${pct(r.refused)} & ${pct(r.unknown)} \\\\`,
      );
    }
    lines.push("\\bottomrule", "\\end{tabular}");
    write("tab_model.tex", lines.join("\n"));
  }

  // ---- Table: top cross-vendor edges (real -> real different vendor) ----
  {
    const top = stats.crossEdges.slice(0, 12);
    const lines = [
      "% AUTO-GENERATED by paper/scripts/gen_tables.ts",
      "\\begin{tabular}{l l r r l}",
      "\\toprule",
      "真实厂商 & 被错认为 & 次数 & 占该厂\\% & 主要语言 (rate) \\\\",
      "\\midrule",
    ];
    for (const e of top) {
      const langs = Object.entries(e.byLang)
        .map(([c, b]) => ({ c, p: b.p }))
        .sort((a, b) => b.p - a.p)
        .slice(0, 2)
        .map((x) => `${tex(lname[x.c] ?? x.c)} ${pct(x.p, 0)}\\%`)
        .join(", ");
      lines.push(
        `${tex(vnames[e.from] ?? e.from)} & ${tex(vnames[e.to] ?? e.to)} & ${e.count} & ${pct(e.probability)} & ${langs} \\\\`,
      );
    }
    lines.push("\\bottomrule", "\\end{tabular}");
    write("tab_edges.tex", lines.join("\n"));
  }

  // ---- Macro file: headline numbers as \newcommand so prose stays in sync ----
  {
    const s = stats.summary;
    const m = stats.meta;
    const bare = stats.byVariant.bare,
      probed = stats.byVariant.probed,
      debrand = stats.byVariant.debrand;
    const def = (name: string, val: string) => `\\newcommand{\\${name}}{${val}}`;
    const lines = [
      "% AUTO-GENERATED headline macros — \\input before \\begin{document}.",
      def("statTotal", String(m.totalAnswers)),
      def("statModels", String(m.nModels)),
      def("statVendors", String(m.nVendors)),
      def("statLangs", String(m.nLanguages)),
      def("statSelf", pct(s.overallSelfRate)),
      def("statCross", pct(s.confusionRate)),
      def("statRefused", pct(s.refusedRate)),
      def("statUnknown", pct(s.unknownRate)),
      def("statBareCross", pct(bare.cross)),
      def("statProbedCross", pct(probed.cross)),
      def("statDebrandCross", pct(debrand.cross)),
      def("statBareSelf", pct(bare.self)),
      def("statDebrandSelf", pct(debrand.self)),
      def("statDebrandRefused", pct(debrand.refused)),
    ];
    write("macros.tex", lines.join("\n"));
  }

  console.log("tables + macros written to paper/tables/");
}

function write(name: string, body: string) {
  const dest = path.join(TABLE_DIR, name);
  fs.writeFileSync(dest, body + "\n", "utf8");
  console.log(`  wrote ${path.relative(REPO_ROOT, dest)}`);
}

main();
